#!/bin/sh

if [ $# -ne 3 ]; then
    echo "Usage: ./create-mtz input.hkl cell_file.cell space_group"
    exit 1
fi

INPUT_HKL=$1
CELL=$2
SPACEGROUP=$3
OUTFILE=$(echo "$INPUT_HKL" | sed -e 's/\.hkl$/.mtz/')

a=$(sed -n 's/^a[[:space:]]*=[[:space:]]*//p' "$CELL" | sed 's/[^0-9.]//g')
b=$(sed -n 's/^b[[:space:]]*=[[:space:]]*//p' "$CELL" | sed 's/[^0-9.]//g')
c=$(sed -n 's/^c[[:space:]]*=[[:space:]]*//p' "$CELL" | sed 's/[^0-9.]//g')
al=$(sed -n 's/^al[[:space:]]*=[[:space:]]*//p' "$CELL" | sed 's/[^0-9.]//g')
be=$(sed -n 's/^be[[:space:]]*=[[:space:]]*//p' "$CELL" | sed 's/[^0-9.]//g')
ga=$(sed -n 's/^ga[[:space:]]*=[[:space:]]*//p' "$CELL" | sed 's/[^0-9.]//g')

echo "Input: $INPUT_HKL; CELL: $a $b $c $al $be $ga; Space group: $SPACEGROUP"
echo "Output: $OUTFILE"

if [ -e create-mtz.temp.hkl ] || [ -e "$OUTFILE" ]; then
    echo "Removing create-mtz.temp.hkl and/or $OUTFILE"
    rm -f create-mtz.temp.hkl "$OUTFILE"
fi

ex -c '/End of reflections/.,$d | w create-mtz.temp.hkl | q!' "$INPUT_HKL"

echo "Running 'f2mtz'..."
f2mtz HKLIN create-mtz.temp.hkl HKLOUT "$OUTFILE" > out.html <<EOF
TITLE Reflections from CrystFEL
NAME PROJECT LOVdarkb9 CRYSTAL LOVdarkb9 DATASET LOVdarkb9
CELL $a $b $c $al $be $ga
SYMM $SPACEGROUP
SKIP 3
LABOUT H K L IMEAN SIGIMEAN
CTYPE  H H H J     Q
FORMAT '(3(F4.0,1X),F10.2,10X,F10.2)'
EOF

# Check result
if [ $? -ne 0 ]; then
    echo "f2mtz failed."
    exit 1
fi

echo "Done."
